- gulpfile.js
> Package fonts

- public/app/config/collections/library/searchTypes.js
- public/app/config/collections/memorials/searchTypes.js
- public/app/config/collections/museum/searchTypes.js
- public/app/config/collections/photographs/searchTypes.js
- test/spec/config/collections/library/searchTypes.spec.js
- test/spec/config/collections/memorials/searchTypes.spec.js
- test/spec/config/collections/museum/searchTypes.spec.js
- test/spec/config/collections/photographs/searchTypes.spec.js
+ Restrict to `ca_occurrences.preferred_labels` to prevent false positives.
> Fix subject search issue.

- public/app/models/ListPager.js
- test/spec/models/ListPager.spec.js
Bugfix
~~Includes #25 so merge that first.~~
> RWAHS-410 Don't go back to start when changing page size

- gulpfile.js
- package.json
- public/robots.txt.staging
- public/robots.txt.uat
+ Staging and UAT `robots.txt` source files.
+ Build step to include the appropriate file.
> Add robots.txt for packaged deployments

- public/app/config/env/staging.js
- public/app/config/env/uat.js
> Use separate API domain names to prevent cookie collision.

- gulpfile.js
> Include build date in `application.js` header.

- public/app/config/collections/memorials/searchTypes.js
- public/app/config/collections/photographs/searchTypes.js
- test/spec/config/collections/memorials/searchTypes.spec.js
- test/spec/config/collections/photographs/searchTypes.spec.js
Also adds creator to public memorials.
> Fix creator search by using correct nested property name.

- public/app/ui/pages/search/search.html
Just adding some simple instructions, more as a starting / talking point than necessarily the correct text.  Client can recommend improvements to the text.
> Add instructions to search form.

- public/app/ui/pages/about/about.html
> Add missing full stop.

- public/app/ui/pages/home/HomePage.less
- public/app/ui/pages/home/home.html
I've put the searches in a list of smaller buttons to the right of the intro text.  In mobile view it drops below as per standard bootstrap.  Happy to change anything here but I think it looks alright.
> Home page changes as requested by client.

- public/app/ui/components/search/results/SearchResultsComponent.js
- public/app/ui/components/search/results/search-results.html
- public/app/ui/pages/search/SearchPage.js
- public/app/ui/pages/search/search.html
> Fix tabular results view

- README.md
The credentials are in the project folder on G:\ under infrastructure.
> Add instructions for deploying the research frontend

- public/app/config/env/development.js
(Unrelated to other pull requests, can be merged any time).
> Prevent caching in `development`.

- public/app/config/env/development.js
- public/app/config/env/production.js
- public/app/config/env/staging.js
- public/app/config/env/uat.js
- public/app/ui/pages/detail/DetailPage.js
- public/app/ui/pages/detail/detail.html
- test/spec/config/env/development.spec.js
- test/spec/config/env/production.spec.js
- test/spec/config/env/staging.spec.js
- test/spec/config/env/uat.spec.js
- test/spec/ui/pages/detail/DetailPage.spec.js
RWAHS-523
Link from detail page to CA backend
Also adds a couple of missing tests.
> Link to backend CA

- package.json
Will self-merge as it is only a version bump and the deployment was discussed elsewhere.
> Version bump `1.0.1`

- public/less/layout.less
Minor change to the cross navigation tabs to match the update of the main website and make it (painfully) obvious there are indeed tabs available.
> Update the colour of the cross tabs

- package.json
> Version bump 1.0.2

- package.json
- public/app/config/env/development.js
- public/app/config/env/production.js
- public/app/config/env/staging.js
- public/app/config/env/uat.js
- public/app/ui/pages/detail/DetailPage.js
- public/app/ui/pages/detail/detail.html
- test/spec/config/env/development.spec.js
- test/spec/config/env/production.spec.js
- test/spec/config/env/staging.spec.js
- test/spec/config/env/uat.spec.js
- test/spec/ui/pages/detail/DetailPage.spec.js
> Link to purchase digital photographs

- public/app/services/searchService.js
- test/spec/services/searchService.spec.js
* Remove quotes as this is not supported by CA.
> Fix `startsWith` and `notStartsWith` operators.

- public/app/ui/components/search/results/SearchResultsComponent.js
- public/app/ui/components/search/results/SearchResultsComponent.less
- public/app/ui/components/search/results/search-results.html
- test/spec/ui/components/search/results/SearchResultsComponent.spec.js
* Add `click` event and callback generator function.
* Add style to indicate clickability.
> Make the whole results row clickable in table view.

- public/app/ui/pages/detail/DetailPage.less
- public/app/ui/pages/detail/detail.html
> Fix link z-index
