README.md
gulpfile.js

+ Make `qa:test` dependent on `qa:lint` so that the tests
are only run if the linter does not return any errors.
+ Make the default task run `qa`, `less` and `watch`.
+ Add documentation about default task.

Improve task dependencies and default task

---

public/app/config/env/development.js
public/app/config/env/staging.js
public/app/config/search/library/resultFields.js
public/app/config/search/memorials/resultFields.js
public/app/config/search/museum/resultFields.js
public/app/config/search/photographs/resultFields.js
public/app/services/searchService.js
public/app/util/safelyParseJson.js
test/main.js
test/spec/services/searchService.spec.js
test/spec/util/safelyParseJson.spec.js

+ Handle invalid JSON by ignoring the value and continuing, rather than crashing.
+ Don't create `li` list items out of empty values (this is a side effect of the way the JSON is constructed on the API end, it will send an array consisting of an empty string when it should send an empty array).
+ Add missing calls to `_.value()`.
+ Display hierarchical values as (visual) hierarchies using `<br/>`, `&nbsp;` and `&rArr;`.
+ Support `noCache` parameter.

RWAHS-308 Improve search config

---

gulpfile.js

+ The `bootstrap` dependency wasn't being included in the packaged `application.js`.
+ This explicitly adds it.

Include `bootstrap` in optimised `application.js`.

---

gulpfile.js

+ Previously, the `package:clean` task was not finishing
before other `package:*` tasks were commencing.
+ This was a misconfiguration of the `gulp` tasks.
+ They are now all dependent on `package:clean`.
+ Similarly with `build:clean`.

Add missing task dependencies.

---

.gitignore
gulpfile.js
package.json

Includes #13 and #14 
Adds a `deploy` task that publishes to S3.
Credentials go in `~/.aws/credentials`.
Note there is a `research-frontend-deploy` user with keys and no password, and a restricted policy, created for this purpose (same user for staging and UAT, can be discussed but doesn't affect the PR).  Keys are on G drive.

Deploy task

---

bower.json
public/app/main.js
test/main.js

This was annoying me for a while now that it was sitting around unused, but I just realised that we probably can't actually use typeahead anyway given the constraints (making an adapter for typeahead that works off the CA web services) and may actually cause performance issues on the CA end.

Remove unused `typeahead.js` dependency.

---

gulpfile.js

This ensures that both `qa` and `build` are successful before allowing `package` or `deploy` to proceed.
Note that `qa` is intentionally not required for `build` because `build` is actually only related to LESS files at this stage; javascript is processed in `package`.

Add missing dependencies in `gulpfile.js`

---

public/app/ui/pages/search/SearchPage.less
public/less/variables.less

+ Use `@alert-warning-bg` and `@gray-lighter` instead of hardcoded colours.
+ Use variables for the image sizes in the three different search result view modes.
+ The `table` view mode and `list` view mode are logically separate so they have
different variables even though the value is the same.

Improve LESS structure, use variables instead of hardcoded values.

---

public/app/models/query/Condition.js
public/app/models/query/Group.js
public/app/services/searchService.js
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/pages/search/SearchPage.js
test/spec/models/query/Group.spec.js
test/spec/services/searchService.spec.js

+ Move the generation of the search query into `searchService` where it belongs.
+ Fix issue with search query generation - use `!` (NOT operator) instead of `-` (prohibit operator).
+ Make everything consistently use `key` (instead of `value`) and `labelText` (instead of `label`).
+ Fix merge issue from previous merge conflict (missing `element` formal arg).
+ Add tests for all the supported comparators.

Clean up search service query generation.

---

public/app/models/query/Condition.js
public/app/models/query/Group.js
public/app/services/searchService.js
public/app/ui/components/search/basic/BasicSearchComponent.js
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/components/search/quick/QuickSearchComponent.js
public/app/ui/pages/search/SearchPage.js
public/app/util/convertBasicSearch.js
test/spec/models/query/Group.spec.js
test/spec/services/searchService.spec.js
test/spec/ui/components/search/quick/QuickSearchComponent.spec.js

Based on #57 please merge that one first.
Make `QuickSearchComponent` generate queries that actually work.
+ The query format was changed, but `QuickSearchComponent` was never updated to correspond.
+ Therefore quick search was not working.
+ This fixes the issue by updating `QuickSearchComponent` to the new format, utilising `convertBasicSearch`.

RWAHS-467 Fix quick search

---

public/app/config/collections/library/searchResultFields.js
public/app/config/collections/museum/searchResultFields.js
test/spec/config/collections/library/searchResultFields.spec.js
test/spec/config/collections/museum/searchResultFields.spec.js

+ Improve label text for `PublicationDate`.
+ Use correct key for `ItemDates`.
+ Remove unused `Classification`.

Clean up search results.

---

public/app/ui/shell.html
public/less/tweaks.less

Remove `collapse` class.
Also, prevent broken layout of tabs and header in mobile view <300px, by setting minimum width of `html` element.

Display tabs in mobile view

---

public/app/util/convertBasicSearch.js
test/spec/util/convertBasicSearch.spec.js

+ Remove extraneous whitespace from query string before splitting.
+ Also add missing tests for this module.

Fix bug: Search terms containing trailing whitespace return no results.

---

public/app/ui/components/search/queryBuilder/QueryBuilderComponent.js
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/pages/search/SearchPage.js
public/app/ui/pages/search/search.html
test/spec/ui/components/search/queryBuilder/QueryBuilderComponent.spec.js

+ Add `keypress` handler that calls `submit` and returns `false` if the enter key is pressed, otherwise does not affect other keypresses.
+ Add missing `.bind()` calls to `SearchPage` view model.
+ Pass `submit` function from binding in `search.html` view .

Make `enter` key submit search rather than adding a condition.

---

package.json
public/app/models/query/Condition.js
public/app/models/query/Group.js
public/app/services/searchService.js
public/app/util/convertBasicSearch.js
test/spec/services/searchService.spec.js
test/spec/util/convertBasicSearch.spec.js

+ There is a `subscribe` loop between the `searchText` observable
and the passed-in `queryObservable`, in the `BasicSearchComponent`.
This allows the search form to function consistently between basic
and advanced search.
+ A recent change introduced a `trim()` call in `convertBasicSearch`,
which is used by one of these `subscribe`s to convert the `searchText`
value into the object structure stored in the `queryObservable`.
+ This `trim()` call was preventing the user from typing a space character,
because it was removed from the query structure, and then removed
from the `searchText` on the return journey.
+ This change removes the `trim()` call, and allows the `Condition` model
to have a falsy value (e.g. empty string), which means that instead of being
removed, the whitespace just …

Fix issue with whitespace in search.

---

public/app/models/ListPager.js
test/spec/models/ListPager.spec.js

Fixes RWAHS-620.
Simple solution to the problem that users want to print all of the given results.  Since the results are limited in the call to the API to 500 maximum, simply giving the option of displaying up to 500 results ensures they are all displayed.

Allow display and printing of all (500) results.

---

public/app/ui/components/search/basic/BasicSearchComponent.js
public/app/ui/components/search/basic/BasicSearchComponent.less
public/app/ui/components/search/basic/basic-search.html
public/app/util/convertBasicSearch.js
public/less/main.less
test/spec/ui/components/search/basic/BasicSearchComponent.spec.js
test/spec/util/convertBasicSearch.spec.js

Fixes RWAHS-633.
+ Display an operator (AND/OR) switch.
+ Pass selected operator back to `convertBasicSearch`.
+ Use correct operator when parsing existing query.
+ Add new stylesheet to `main.less`.

Provide operator switch in basic search mode.

---

public/app/models/query/Group.js
public/app/ui/components/search/queryBuilder/QueryBuilderComponent.less
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/pages/search/SearchPage.js
public/app/ui/pages/search/search.html
test/spec/models/query/Group.spec.js
test/spec/ui/pages/search/SearchPage.spec.js

Fixes RWAHS-582 and RWAHS-621.
+ Improve icons and text used on "add" / "remove" buttons.
+ Display current modified query in query builder.
+ Display number of results.
+ Display query used for current search (previously only for print).
+ Don't display a "remove" button for the top-level group.
+ Add missing `bind`ing in `Group.js`.
+ Add missing `width` and `max-width` rules for condition form elements.

Improvements to query builder.

---

public/app/config/env/development.js
public/app/config/env/production.js
public/app/config/env/staging.js
public/app/config/env/uat.js
public/app/models/query/Group.js
public/app/ui/components/search/queryBuilder/QueryBuilderComponent.less
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/pages/detail/DetailPage.js
public/app/ui/pages/search/SearchPage.js
public/app/ui/pages/search/search.html
test/spec/models/query/Group.spec.js
test/spec/ui/pages/detail/DetailPage.spec.js
test/spec/ui/pages/search/SearchPage.spec.js

Fixes RWAHS-606.
Includes #87 please merge that one first.
When the shop configuration is supplied, and a search is executed, a link is provided to the shop for the same search query.
This uses only top-level terms from advanced searches, nested terms are ignored.

Link to shop search

---

public/app/config/comparators.js
public/app/config/settings.js
public/app/models/query/Condition.js
public/app/services/searchService.js
public/app/ui/components/search/basic/BasicSearchComponent.js
public/app/ui/components/search/queryBuilder/QueryBuilderComponent.js
public/app/ui/components/search/queryBuilder/query-builder.html
public/app/ui/pages/search/SearchPage.js
public/app/ui/pages/search/search.html
public/app/util/convertBasicSearch.js
test/fixtures/comparators.js
test/spec/config/settings.spec.js
test/spec/models/query/Condition.spec.js
test/spec/services/searchService.spec.js
test/spec/ui/components/search/basic/BasicSearchComponent.spec.js
test/spec/ui/components/search/queryBuilder/QueryBuilderComponent.spec.js
test/spec/ui/pages/search/SearchPage.spec.js

+ Add `valueType` parameter in `Condition` to determine whether
the field should be displayed.
+ Use `valueTypeIs` function to toggle display fo `value` field.
+ Add templates in `searchService` for new operators.
+ Remove `filter` call in `searchService`; this was causing empty
values to be omitted, which caused an inconsistent result on
browser page reload.

Support for `empty` and `notEmpty` operators.

---

public/app/config/env/development.js
public/app/ui/pages/detail/detail.html
public/app/ui/pages/search/search.html

RWAHS-644
+ Added to `search` and `detail` pages only.
+ Simply calls `window.print()`.
+ Actual print styling already handled by print stylesheet.

Add print buttons.

---

public/app/ui/pages/search/SearchPage.js

+ Filter to remove empty constraints should be applied
on display only.
+ Remove unwanted `console.log`.

Fix filtering issue causing whitespace swallowing.
